feat: TryFrom ptr-size
rkyv/rend pull request #11
Opened 2024-02-22 19:28 UTC by Alxandr

2024-02-22 21:00 UTC, djkoloski requested changes

2024-02-22 21:00 UTC, djkoloski commented on src/traits.rs
> +    (Into<$size:ty> for $name:ident via $prim:ty) => {
Since `$prim` isn't used here, we can shorten this to `($size:ty for $name:ident)`. I'd also prefer that this be separated into a `macro_rules! impl_into` macro.

2024-02-22 21:00 UTC, djkoloski commented on src/traits.rs
> +    (for $name:ident: TryFrom<$size:ty> via $prim:ty) => {
I would prefer this as `macro_rules! impl_try_from` with the arm being `($size:ty for $name:ident: $prim:ty)`. It's a little more consistent with how the other macros are written.

2024-02-22 21:00 UTC, djkoloski commented on src/traits.rs
> +        impl_try_into_ptr_size!(Into<usize> for $name via i16);
```suggestion
        impl_try_into_ptr_size!(Into<usize> for $name via u16);
```

2024-02-22 21:00 UTC, djkoloski commented on src/lib.rs
> +impl_try_into_ptr_size!(TryInto<isize> for i16_le via i16);
I think these can be merged into the `impl_signed_integer_traits` macro instead of being defined separately.

2024-02-22 21:00 UTC, djkoloski commented on src/lib.rs
> +impl_try_into_ptr_size!(TryInto<usize> for u16_le via u16);
Same here for the unsigned integer impl macro.

2024-02-22 21:06 UTC, Alxandr commented on src/traits.rs
> +    (for $name:ident: TryFrom<$size:ty> via $prim:ty) => {
This is not legal. You're not allowed to put `for` after a `ty` binding.

2024-02-22 21:07 UTC, Alxandr commented on src/traits.rs
> +        impl_try_into_ptr_size!(Into<usize> for $name via i16);
Ah - stupid oversight. But as you suggested previously, I've removed the `via` clause for `Into`, so this part is gone.

2024-02-22 21:08 UTC, Alxandr commented on src/lib.rs
> +impl_try_into_ptr_size!(TryInto<isize> for i16_le via i16);
Unfortunately, as far as I could figure out, that's not the case (it's what I tried first). The issue is that once you bind a type as `$whatever:ty`, you can no longer match it to (for instance) `isize`. So there is no way to deal with the two that should be `Into` and not `TryInto`.

2024-02-22 21:09 UTC, Alxandr commented on src/lib.rs
> +impl_try_into_ptr_size!(TryInto<usize> for u16_le via u16);
Same as above, I don't believe it's possible. At least I don't know how.

2024-02-22 21:10 UTC, Alxandr commented on src/traits.rs
> +    (Into<$size:ty> for $name:ident via $prim:ty) => {
Sone.

2024-02-23 01:32 UTC, djkoloski approved these changes

2024-02-23 01:34 UTC, merged